export const HOME_GET_ABOUT_BEGIN = 'HOME_GET_ABOUT_BEGIN';
export const HOME_GET_ABOUT_SUCCESS = 'HOME_GET_ABOUT_SUCCESS';
export const HOME_GET_ABOUT_FAILURE = 'HOME_GET_ABOUT_FAILURE';
export const HOME_GET_ABOUT_DISMISS_ERROR = 'HOME_GET_ABOUT_DISMISS_ERROR';
